import { ArrowDownRight, ArrowRight, CircuitBoard, Layers3, ScanLine } from "lucide-react";
import { Navigation } from "@/components/Navigation";
import { CinematicStory } from "@/components/CinematicStory";
import { Reveal } from "@/components/Reveal";
import { SectionHeader } from "@/components/SectionHeader";
import { ProductShowcase } from "@/components/ProductShowcase";
import { FeedbackForm } from "@/components/FeedbackForm";
import { Footer } from "@/components/Footer";
import { mailto, siteConfig } from "@/config/site";

const approach = [
  ["01", "UPLOAD", "Architectural drawing."],
  ["02", "UNDERSTAND", "Rooms · Walls · Doors · Windows · Geometry"],
  ["03", "DESIGN", "Generate an electrical first draft using structured geometry and engineering rules."],
  ["04", "REVIEW", "Engineer verifies and edits."],
  ["05", "OUTPUT", "Electrical layout · BOQ · Structured engineering data"],
];
const capabilities = ["Architectural Plan Input", "Room Geometry", "Opening Detection", "Structured Plan Data", "Electrical Rule Engine", "Electrical Layout Generation", "BOQ Generation"];

export default function Home() { return <main>
  <Navigation/><CinematicStory/>
  <section className="section productIntro blueprint" id="product"><Reveal><SectionHeader eyebrow="PHASE 01 / BUILDING NOW" title={<>AI-NATIVE<br/>ELECTRICAL DESIGN.</>}/></Reveal><Reveal delay={.1}><div className="introGrid"><p className="lede">We are building a system that interprets architectural drawings and creates structured electrical engineering first drafts for engineer review.</p><div className="actions"><a className="button primary" href="#prototype">Explore the prototype <ArrowDownRight/></a><a className="textLink" href="#feedback">Share your workflow <ArrowRight/></a></div></div></Reveal></section>
  <section className="section" aria-labelledby="problem-title"><Reveal><SectionHeader eyebrow="THE PROBLEM" title={<>ENGINEERING SOFTWARE EVOLVED.<br/>THE WORKFLOW STILL HAS FRICTION.</>} id="problem-title"/></Reveal><div className="splitCopy"><Reveal><p>Engineering teams still interpret architectural drawings, reconstruct building information, design systems, calculate quantities, coordinate changes and revise documentation.</p></Reveal><Reveal delay={.08}><p>The drawing is digital. Much of the reasoning around it is still rebuilt by hand.</p></Reveal></div><Reveal><div className="processStrip">{["ARCHITECTURAL DRAWING","INTERPRET","DESIGN","COORDINATE","QUANTIFY","REVISE"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}{i<5&&<ArrowRight/>}</div>)}</div></Reveal><Reveal><p className="statement">WHAT IF THE DRAWING BECAME<br/><em>STRUCTURED ENGINEERING DATA</em> FIRST?</p></Reveal></section>
  <section className="section approach" id="approach"><Reveal><SectionHeader eyebrow="OUR APPROACH" title={<>UNDERSTAND FIRST.<br/>ENGINEER SECOND.</>}/></Reveal><div className="approachFlow">{approach.map(([n,t,d],i)=><Reveal delay={i*.04} key={n}><article><span className="stepNumber">{n}</span><ScanLine/><h3>{t}</h3><p>{d}</p></article></Reveal>)}</div></section>
  <section className="section" id="prototype"><Reveal><SectionHeader eyebrow="PHASE 01 / BUILDING NOW" title={<>STARTING WITH<br/>ELECTRICAL.</>}/></Reveal><Reveal><p className="lede narrow">Our current prototype focuses on understanding architectural plans and using that structured geometry as the foundation for electrical design.</p></Reveal><ProductShowcase/><Reveal><div className="capabilities"><div><span className="eyebrow">CURRENT CAPABILITIES</span><p>Technical areas being developed in the prototype.</p></div><ul>{capabilities.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,"0")}</span>{item}<b>BUILDING</b></li>)}</ul></div></Reveal></section>
  <section className="section controlSection"><Reveal><SectionHeader eyebrow="HUMAN CONTROL" title={<>AI CREATES THE FIRST DRAFT.<br/>ENGINEERS STAY IN CONTROL.</>}/></Reveal><div className="controlFlow">{[["AI","UNDERSTANDS GEOMETRY"],["AI","PROPOSES LAYOUT"],["ENGINEER","REVIEWS"],["ENGINEER","MODIFIES"],["ENGINEER","APPROVES"],["OUTPUT","ENGINEERING DOCUMENTS"]].map(([role,action],i)=><Reveal delay={i*.035} key={action}><div><small>{role}</small><strong>{action}</strong>{i<5&&<ArrowRight/>}</div></Reveal>)}</div></section>
  <section className="section editorial"><Reveal><p className="eyebrow">WHY IT MATTERS</p><h2>ENGINEERS SHOULD<br/><span>ENGINEER.</span></h2><p>Not repeatedly reconstruct information that already exists in the drawing.</p><p className="editorialNote">We are exploring a workflow where drawings first become structured building information, allowing engineering systems to be created and reviewed on top of shared geometry.</p></Reveal></section>
  <section className="section vision" id="vision"><Reveal><SectionHeader eyebrow="THE VISION" title={<>ONE BUILDING.<br/>EVERY ENGINEERING SYSTEM.</>}/></Reveal><Reveal><div className="visionLayers"><div className="layer architecture"><Layers3/>ARCHITECTURE <small>INPUT</small></div><div className="layer electrical"><CircuitBoard/>ELECTRICAL <small>BUILDING NOW</small></div>{["PLUMBING","HVAC","STRUCTURAL"].map(x=><div className="layer roadmap" key={x}>{x}<small>ROADMAP</small></div>)}<div className="layer model">COORDINATED 3D MODEL <small>VISION</small></div></div></Reveal><Reveal><div className="sharedModel"><h3>A SHARED MODEL<br/>OF THE PHYSICAL WORLD.</h3><div className="modelDiagram"><div>ARCHITECTURE</div><i/><div className="core">SHARED BUILDING MODEL</div><i/><div className="disciplines"><span className="active">ELECTRICAL</span><span>PLUMBING</span><span>HVAC</span><span>STRUCTURAL</span></div><i/><div>COORDINATED ENGINEERING MODEL</div></div></div></Reveal></section>
  <section className="section discovery" id="feedback"><Reveal><SectionHeader eyebrow="WE'RE LISTENING" title={<>HOW DOES YOUR TEAM<br/>DO THIS TODAY?</>}/></Reveal><Reveal><div className="discoveryCopy"><p className="lede">We&apos;re speaking with engineering and construction teams to understand where time is actually lost between receiving architectural drawings and producing engineering designs.</p><p>We would rather learn from engineers than guess.</p></div></Reveal><FeedbackForm/></section>
  <section className="section finalCta"><Reveal><span className="eyebrow">OPEN CONVERSATION</span><h2>BUILDING THE NEXT<br/>ENGINEERING WORKFLOW.</h2><p>If your team works with architectural drawings, electrical design, MEP coordination or BIM, we&apos;d like to learn how you work.</p><a className="button primary" href={mailto}>Talk to us <ArrowRight/></a><a className="contactEmail" href={mailto}>{siteConfig.email}</a></Reveal></section><Footer/>
</main> }
