"use client";

import { motion, useTransform } from "framer-motion";
import { Box } from "lucide-react";
import { usePinnedProgress } from "@/hooks/usePinnedProgress";

const steps = [
  { title: "Model", caption: "From drawings to spatial engineering.", alt: "Reference BIM wireframe showing building systems across multiple floors" },
  { title: "Coordinate", caption: "Equipment, services, and routes—in context.", alt: "Reference engineering model with coordinated equipment and colorful service routes" },
  { title: "Building scale", caption: "The engineering model becomes the workspace.", alt: "Reference building-scale BIM model showing coordinated structures and building systems" },
];

export function VisionStory() {
  const { ref, progress, active, choose, manual, reduced, visible } = usePinnedProgress(3, true);
  const opacity1 = useTransform(progress, [.26, .43], [1,0]);
  const opacity2 = useTransform(progress, [.26, .43, .6, .78], [0,1,1,0]);
  const opacity3 = useTransform(progress, [.6, .78], [0,1]);
  const mask2 = useTransform(progress, [.26,.43], ["inset(0 100% 0 0)","inset(0 0% 0 0)"]);
  const mask3 = useTransform(progress, [.6,.78], ["inset(0 0 0 100%)","inset(0 0 0 0%)"]);
  const scale = useTransform(progress, [0,1], [1.025,1]);

  return <section className="pinned-story vision-story" id="spatial-vision" ref={ref} data-stage={active + 1}>
    <div className="story-sticky section-shell">
      <div className="demo-heading"><div><p className="section-kicker"><Box/> Vision / Next</p><h2>Beyond the plan.<br className="mobile-break"/> <em>Into the building.</em></h2></div><p>From editable 2D engineering<br/>toward 3D coordination.</p></div>
      <div className="vision-frame"><div className="app-bar"><span className="window-dots"><i/><i/><i/></span><span>3D engineering direction</span><span className="frame-status">Vision reference / {String(active + 1).padStart(2,"0")}</span></div><div className="vision-images">
        {steps.map((step,index) => {
          const props = { src:`/vision/reference-${index+1}.webp`, alt:step.alt, width:index===0?1549:1200, height:index===0?807:index===1?800:909, "aria-hidden":active!==index };
          // Native styles keep touch/reduced-motion stages independent of scroll MotionValues.
          return manual ? <img key={step.title} {...props} loading={visible?"eager":"lazy"} style={{opacity:active===index?1:0}}/>
            : <motion.img key={step.title} {...props} loading={visible?"eager":"lazy"} style={{opacity:index===1?opacity2:index===2?opacity3:opacity1, clipPath:index===1?mask2:index===2?mask3:undefined, scale:reduced?1:scale}}/>;
        })}
        <span className="vision-disclosure">Supplied visual references · not generated by our product</span>
      </div></div>
      <div className="demo-bottom"><div className="stage-tabs" aria-label="3D vision stages">{steps.map((step,index) => <button key={step.title} onClick={()=>choose(index)} aria-current={active===index?"step":undefined}><span>0{index+1}</span>{step.title}</button>)}</div><p>{steps[active].caption}</p></div>
      <p className="vision-status">Interactive 3D is a future milestone. Today’s working product is the editable 2D electrical workflow.</p>
    </div>
  </section>;
}
